# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: /dcs/large/u2034358/ntu/NTU60_CV_aligned.npz
  label_path: None
  p_interval: [0.95]
  split: 'test'
  random_choose: False
  random_shift: False
  random_move: False
  random_rot: True
  window_size: -1
  normalization: False
  debug: False
  use_mmap: False
  vel: False
  sort: False
  repeat: True

# model
model: model.agcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'
  d: 8
  PE_name: 'checkpoint_betaNAPE_ntu-sb.pt'
  use_PE: True


# test 
phase: test
device: [0,1]
test_batch_size: 256
weights: ./runs-NAPE/ntu_cv_agcn_train_joint-49-29400.pt

work_dir: ./work_dir-NAPE/ntu/xview/agcn_test_joint
model_saved_name: ./runs-NAPE/ntu_cv_agcn_test_joint
save_score: True